= take-remote-control

Prise de contrôle à distance pour activer/désactiver le clavier et la souris de plusieurs ordinateurs en réseau, sous Linux

La prise de contrôle s'effectue par l'exécution de commandes à distance sur chacun des postes, en utilisant le protocole SSH.

== Prérequis

* Les ordinateurs doivent avoir une distribution de Linux identique.
* Les ordinateurs doivent avoir une configuration identique.
* Chaque poste devra avoir SSH installé.
** Pour tester l'existence de cete commande, ouvrir un terminal et taper 'ssh'
** Si la commande n'est pas installée, taper : sudo apt-get install openssh

On devra installer la clé SSH du poste qui va prendre le contrôle sur chacun des postes, afin de faciliter les échanges.

=== Générer la clé SSH du poste qui va prendre le contrôle des autres

On doit générer une clé privée et une clé publique pour échanger notre clé publique avec les autres postes afin que l'on puisse ensuite y lancer des commandes

Pour cela, ouvrir un terminal et taper :

```
ssh-keygen -t rsa
```

La commande va proposer de créer une passphrase, c'est à dire un mot de passe associé à la clé.
*Il est vivement conseillé de la laisser vide*, sinon il sera demandé à chaque exécution de commande distante.

=== Installer la clé SSH sur les postes qui devront être contrôlés

Pour installer la clé SSH sur les postes, lancer la commande suivante *_pour chacun des postes distants_*, depuis le poste de contrôle :

```
ssh-copy-id -i ~/.ssh/id_rsa.pub utilisateur@adresse_ip_poste_distant
```

La commande demande juste le mot de passe de l'utilisateur distant afin de valider l'opération

=== Comprendre comment fonctionne cette prise de contrôle

Le script de contrôle va activer ou désactiver les driver du clavier et de la souris.

== Télécharger le script sur le poste de contrôle

Il est possible de télécharger le script de deux manières différentes :

* De manière standard avec git : git clone https://github.com/vdubois/take-remote-control
* Ou en le téléchargeant en cliquant sur le lien "clone or download" > "download zip" en haut à droite de l'écran

== Configurer le script

Ouvrir le script take-remote-control.sh avec un éditeur de texte et personnaliser les valeurs suivantes :

* L'ensemble des adresses IP des postes à contrôler (ligne 4 du script)
* UTILISATEUR (l'utilisateur Linux des postes à contrôler, celui avec lequel vous avez copié la clé SSH du poste de contrôle)
* MDP (le mot de passe de l'utilisateur Linux des postes à contrôler)

== Vérifier que le script soit exécutable

Afin de s'assurer que le script soit exécutable, ouvrir un terminal et taper :

```
cd répertoire_contenant_le_script
chmod +x take-remote-control.sh
```

== Lancer le script

Pour désactiver souris et claviers sur les postes distants :

```
cd répertoire_contenant_le_script
./take-remote-control.sh disable
```

Pour les réactiver :

```
./take-remote-control.sh enable
```
